shared:
  image: rust:1.51

jobs:
  pr:
    requires: [~pr]
    steps:
      - run_arbitrary_script: apt-get update && apt-get -y install clang openssl && rustup component add rustfmt && cargo check && cargo test -- --test-threads=1 
  main:
    requires: [~commit]
    steps:
      - run_arbitrary_script: apt-get update && apt-get -y install clang openssl && rustup component add rustfmt && cargo test -- --test-threads=1 && cargo build
    secrets:
      - CI_DEPLOY_USERNAME
      - CI_DEPLOY_PASSWORD
      - DOCKER_EMAIL
      - DOCKER_REPO
      - DOCKER_PASSWORD
      - DOCKER_REPOSITORY
      - DOCKER_USERNAME
    annotations:
      screwdriver.cd/dockerEnabled: true
  publish:
    requires: [~main]
    steps:
      - build_image: apt-get update && apt-get install docker-ce docker-ce-cli containerd.io && docker build . -t opentsdb-meta
    annotations:
      screwdriver.cd/dockerEnabled: true
  publish-docs:
    requires: [~main]
    steps:
      - publish: rustup component add rustfmt && cargo doc && echo '<meta http-equiv=refresh content=0;url=YOURLIBNAME/index.md>' > target/doc/index.html && sudo pip install ghp-import && ghp-import -n target/doc && git push -qf https://github.com/OpenTSDB/opentsdb-meta.git gh-pages

