shared:
  image: rust:1.51

jobs:
  pr:
    requires: [~pr]
    steps:
      - run_arbitrary_script: apt-get update && apt-get -y install clang openssl && rustup component add rustfmt && cargo check && cargo test -- --test-threads=1 
  main:
    requires: [~commit]
    steps:
      - run_arbitrary_script: apt-get update && apt-get -y install clang openssl && rustup component add rustfmt && cargo build
    secrets:
      - CI_DEPLOY_USERNAME
      - CI_DEPLOY_PASSWORD
      - DOCKER_EMAIL
      - DOCKER_REPO
      - DOCKER_PASSWORD
      - DOCKER_REPOSITORY
      - DOCKER_USERNAME
    annotations:
      screwdriver.cd/dockerEnabled: true
   publish:
     requires: [~main]
     steps: docker build . -t opentsdb-meta
     annotations:
       screwdriver.cd/dockerEnabled: true

