shared:
  image: rust:1.51

jobs:
  pr:
    requires: [~pr]
    steps:
      - run_arbitrary_script: apt-get update && apt-get -y install clang openssl && rustup component add rustfmt && cargo check && cargo test -- --test-threads=1 
  main:
    requires: [~commit]
    steps:
      - run_arbitrary_script: echo $DOCKER_USERNAME $DOCKER_REPO
    secrets:
      - CI_DEPLOY_USERNAME
      - CI_DEPLOY_PASSWORD
      - DOCKER_EMAIL
      - DOCKER_REPO
      - DOCKER_PASSWORD
      - DOCKER_REPOSITORY
      - DOCKER_USERNAME
    annotations:
      screwdriver.cd/dockerEnabled: true
  publish:
    requires: [~main]
    steps:
      - create_tag:
          /bin/bash create_git_tag.sh
      - build_and_publish_image:
          echo $DOCKER_USERNAME
         
    annotations:
      screwdriver.cd/dockerEnabled: true
    secrets:
      - DOCKER_EMAIL
      - DOCKER_PASSWORD
      - DOCKER_USERNAME
      - GITHUB_TOKEN
